language: php

sudo: false

cache:
    yarn: true
    directories:
        - $HOME/.composer/cache
        - $HOME/symfony-bridge/.phpunit
        - node_modules

php:
    - '7.3'
    - '7.4'

install:
    - composer install
    - yarn install

before_script:
    - yarn build
    - php bin/console doctrine:database:create --env=test

script:
    - ./vendor/bin/phpstan analyse
    - ./vendor/bin/simple-phpunit
