os: linux

language: php

php:
    - 7.4

services:
    - docker

cache:
    yarn: true
    directories:
        - ./bin/.phpunit
        - node_modules

env:
    - DOCKER_COMPOSE_VERSION=3.6
    global:
        - PATH="$HOME/.symfony/bin:$PATH"

before_install:
    - docker-compose up -d

install:
    - make install

before_script:
    - phpenv config-rm xdebug.ini

script:
    - ./vendor/bin/phpstan analyse
    - ./vendor/bin/php-cs-fixer fix --diff --diff-format=udiff --dry-run --no-interaction --ansi
    - make ci
