os: linux

language: php

php:
    - 7.4

node_js:
    - 12

cache:
    yarn: true
    directories:
        - $HOME/.symfony
        - $HOME/.composer/cache/files
        - ./bin/.phpunit
        - node_modules

env:
    global:
        - PATH="$HOME/.symfony/bin:$PATH"

before_install:
    - if symfony self:version; then symfony self:update --yes ; else wget https://get.symfony.com/cli/installer -O - | bash ; fi

install:
    - composer install
    - ./bin/phpunit install
    - yarn install

before_script:
    - phpenv config-rm xdebug.ini
    - yarn build
    - symfony console doctrine:database:create --env=test

script:
    - ./vendor/bin/phpstan analyse
    - ./vendor/bin/php-cs-fixer fix --diff --diff-format=udiff --dry-run --no-interaction --ansi
    - make ci
