language: php

os: linux

cache:
    yarn: true
    directories:
        - $HOME/.symfony
        - $HOME/.composer/cache/files
        - ./bin/.phpunit
        - node_modules

env:
    global:
        - PATH="$HOME/.symfony/bin:$PATH"

php:
    - '7.4'

before_install:
    - if symfony self:version; then symfony self:update --yes ; else wget https://get.symfony.com/cli/installer -O - | bash ; fi

install:
    - composer install
    - yarn install

before_script:
    - phpenv config-rm xdebug.ini
    - yarn build
    - symfony bin/console doctrine:database:create --env=test

script:
    - make lint
    - ./vendor/bin/phpstan analyse
    - ./vendor/bin/simple-phpunit
    - symfony console doctrine:schema:validate --skip-sync -vvv --no-interaction
    - symfony check:security
