version: '3.6'

services:
  caddy:
    image: caddy:2
    container_name: symforum_caddy
    environment:
      SERVER_NAME: ${SERVER_NAME:-symforum.localhost, caddy:80}
    ports:
      - 80:80
      - 443:443
    working_dir: /var/www/html
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php

  php:
    build: docker/php/7.4-fpm-dev
    container_name: symforum_php
    user: '1000:1000'
    env_file:
      - .env
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:rw,cached
      - ./docker/php/symfony.dev.ini:/etc/php7/conf.d/symfony.ini

  database:
    image: mysql:8
    container_name: symforum_database
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - database_data:/var/lib/mysql

volumes:
  caddy_data:
  caddy_config:
  database_data:
