version: '3.6'

services:
  nginx:
    image: nginx:alpine
    container_name: symforum_nginx
    ports:
      - 80:80
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:rw,cached
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build: docker/php/7.4-fpm-dev
    container_name: symforum_php
    user: '1000:1000'
    env_file:
      - .env
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:rw,cached
      - ./docker/php/symfony.dev.ini:/etc/php7/conf.d/symfony.ini

  database:
    image: mysql:8
    container_name: symforum_database
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
